Task-1: Config and release
natali-maximenko/level_up pull request #1
Opened 2022-02-07 13:15 UTC by natali-maximenko

2022-02-08 17:50 UTC, Apelsinka223 requested changes
Небольшое замечание, а в остальном все идеально ❤️

2022-02-08 17:50 UTC, Apelsinka223 commented on config/prod.exs
> +config :level_up, contact_email: System.fetch_env!("CONTACT_EMAIL")
По заданию это верно, но т.к. нас интересует глубокое понимание, не стоит запрашивать переменные окружения в конфиге кроме runtime.exs. Два варианта сделать правильно:
- вынести эту строку в runtime.exs, и добавить проверку что запущено окружение prod
- не вызывать функцию в файле конфига, а только обозначить что требуется переменная окружения (например `{:system, "CONTACT_EMAIL"}` и вызывать саму функцию уже внутри модуля.

Раньше когда не было runtime.exs использовался второй вариант, но сейчас принято пользоваться первым вариантом

2022-02-08 17:50 UTC, Apelsinka223 commented on test/level_up_test.exs
> +    assert LevelUp.contact_email() == "test@elixirschool.com"
Отлично что написала тест 💪

2022-02-08 17:50 UTC, Apelsinka223 commented on Dockerfile
> +ENV CONTACT_EMAIL=release@elixirschool.com
Супер, не забыла про переменную 👏

2022-02-09 07:50 UTC, natali-maximenko commented on config/prod.exs
> +config :level_up, contact_email: System.fetch_env!("CONTACT_EMAIL")
Исправила

2022-02-09 08:05 UTC, Apelsinka223 approved these changes

2022-02-09 08:26 UTC, merged