Task-2: Macros
natali-maximenko/level_up pull request #2
Opened 2022-02-11 07:59 UTC by natali-maximenko

2022-02-14 15:10 UTC, Apelsinka223 requested changes

2022-02-14 15:10 UTC, Apelsinka223 commented on lib/level_up/macros.ex
> +  defmacro case_if(condition) do
В if кроме condition есть еще и два блока с кодом, который должен выполняться в зависимости от условия:
```
if *condition* do
  *block true*
else
  *block false*
end
```
Блок кода в Эликсире является таким же аргументом макроса как и обычные значения. Сам defmacro является макросом, принимающим на вход 2 аргумента, и эту строку можно переписать в таком виде:
`defmacro(:case_if, do: ...)`. Также как и стандартный if может быть записан в таком виде:
```
if(*condition*, do: *block true*, else: *block false*)
```
Не очевидный момент, ключевые слова `do`, `else` и тд также превращаются в атомы и вместе представляют собой аргумент - Keyword list.
Вот тут подробные примеры про то как это все работает https://thepugautomatic.com/2015/12/elixir-block-keywords/

2022-02-14 15:10 UTC, Apelsinka223 commented on lib/level_up/macros.ex
> +        label: "called from #{function}/#{arity} in module #{info.module} on line #{info.line}"
👍

2022-02-14 15:10 UTC, Apelsinka223 commented on lib/level_up/macros.ex
> +      if match?(unquote(pattern), unquote(code)), do: true, else: unquote(message)
👍

2022-02-14 15:10 UTC, Apelsinka223 commented on test/level_up/macros_test.exs
> +      assert true == LevelUp.Macros.assert_match(^x, {:ok, 1}, "expected x to match {:ok, 1}")
👍

2022-02-15 07:13 UTC, natali-maximenko commented on lib/level_up/macros.ex
> +  defmacro case_if(condition) do
Ага, спасибо. Исправила

2022-02-16 11:48 UTC, Apelsinka223 approved these changes

2022-02-16 13:57 UTC, merged